name: "Driver Build"
on:
  push:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.8.1
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Install CMake
        run: choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"'

      - name: Verify CMake installation
        run: cmake --version




